<?php

namespace ContainerF3DX2SS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZCabcbbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZCabcbb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZCabcbb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FavoriteController::toggleFavorite' => ['privates', '.service_locator.ALZKgL8.App\\Controller\\FavoriteController::toggleFavorite()', 'getFavoriteControllertoggleFavoriteService', true],
            'App\\Controller\\PropositionController::index' => ['privates', '.service_locator.JokWpGs.App\\Controller\\PropositionController::index()', 'getPropositionControllerindexService', true],
            'App\\Controller\\PropositionController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\PropositionController::new()', 'getPropositionControllernewService', true],
            'App\\Controller\\PropositionController::show' => ['privates', '.service_locator.S6XjvRR.App\\Controller\\PropositionController::show()', 'getPropositionControllershowService', true],
            'App\\Controller\\PropositionController::edit' => ['privates', '.service_locator.2i0aRz0.App\\Controller\\PropositionController::edit()', 'getPropositionControllereditService', true],
            'App\\Controller\\PropositionController::delete' => ['privates', '.service_locator.2i0aRz0.App\\Controller\\PropositionController::delete()', 'getPropositionControllerdeleteService', true],
            'App\\Controller\\PropositionController::apiList' => ['privates', '.service_locator.JokWpGs.App\\Controller\\PropositionController::apiList()', 'getPropositionControllerapiListService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\FavoriteController:toggleFavorite' => ['privates', '.service_locator.ALZKgL8.App\\Controller\\FavoriteController::toggleFavorite()', 'getFavoriteControllertoggleFavoriteService', true],
            'App\\Controller\\PropositionController:index' => ['privates', '.service_locator.JokWpGs.App\\Controller\\PropositionController::index()', 'getPropositionControllerindexService', true],
            'App\\Controller\\PropositionController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\PropositionController::new()', 'getPropositionControllernewService', true],
            'App\\Controller\\PropositionController:show' => ['privates', '.service_locator.S6XjvRR.App\\Controller\\PropositionController::show()', 'getPropositionControllershowService', true],
            'App\\Controller\\PropositionController:edit' => ['privates', '.service_locator.2i0aRz0.App\\Controller\\PropositionController::edit()', 'getPropositionControllereditService', true],
            'App\\Controller\\PropositionController:delete' => ['privates', '.service_locator.2i0aRz0.App\\Controller\\PropositionController::delete()', 'getPropositionControllerdeleteService', true],
            'App\\Controller\\PropositionController:apiList' => ['privates', '.service_locator.JokWpGs.App\\Controller\\PropositionController::apiList()', 'getPropositionControllerapiListService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\FavoriteController::toggleFavorite' => '?',
            'App\\Controller\\PropositionController::index' => '?',
            'App\\Controller\\PropositionController::new' => '?',
            'App\\Controller\\PropositionController::show' => '?',
            'App\\Controller\\PropositionController::edit' => '?',
            'App\\Controller\\PropositionController::delete' => '?',
            'App\\Controller\\PropositionController::apiList' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\FavoriteController:toggleFavorite' => '?',
            'App\\Controller\\PropositionController:index' => '?',
            'App\\Controller\\PropositionController:new' => '?',
            'App\\Controller\\PropositionController:show' => '?',
            'App\\Controller\\PropositionController:edit' => '?',
            'App\\Controller\\PropositionController:delete' => '?',
            'App\\Controller\\PropositionController:apiList' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
