<?php

namespace ContainerF3DX2SS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JokWpGsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JokWpGs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JokWpGs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'propositionRepository' => ['privates', 'App\\Repository\\PropositionRepository', 'getPropositionRepositoryService', true],
        ], [
            'propositionRepository' => 'App\\Repository\\PropositionRepository',
        ]);
    }
}
