<?php

namespace ContainerF3DX2SS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropositionControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2i0aRz0.App\Controller\PropositionController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.2i0aRz0'] ?? $container->load('get_ServiceLocator_2i0aRz0Service'));

        if (isset($container->privates['.service_locator.2i0aRz0.App\\Controller\\PropositionController::edit()'])) {
            return $container->privates['.service_locator.2i0aRz0.App\\Controller\\PropositionController::edit()'];
        }

        return $container->privates['.service_locator.2i0aRz0.App\\Controller\\PropositionController::edit()'] = $a->withContext('App\\Controller\\PropositionController::edit()', $container);
    }
}
