<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'favorites' => [parent::class, 'favorites', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'infosUser' => [parent::class, 'infosUser', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'propositions' => [parent::class, 'propositions', null, 16],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'favorites' => [parent::class, 'favorites', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'infosUser' => [parent::class, 'infosUser', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'propositions' => [parent::class, 'propositions', null, 16],
        'roles' => [parent::class, 'roles', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
