<?php

namespace ContainerX69eX5x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriteControllertoggleFavoriteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ALZKgL8.App\Controller\FavoriteController::toggleFavorite()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ALZKgL8.App\\Controller\\FavoriteController::toggleFavorite()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'proposition' => ['privates', 'App\\Entity\\Proposition', 'getPropositionService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'proposition' => 'App\\Entity\\Proposition',
            'em' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\FavoriteController::toggleFavorite()', $container);
    }
}
