<?php

namespace ContainerX69eX5x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropositionControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S6XjvRR.App\Controller\PropositionController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S6XjvRR.App\\Controller\\PropositionController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'proposition' => ['privates', 'App\\Entity\\Proposition', 'getPropositionService', true],
        ], [
            'proposition' => 'App\\Entity\\Proposition',
        ]))->withContext('App\\Controller\\PropositionController::show()', $container);
    }
}
