<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX69eX5x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX69eX5x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX69eX5x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX69eX5x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX69eX5x\App_KernelDevDebugContainer([
    'container.build_hash' => 'X69eX5x',
    'container.build_id' => 'e7de2871',
    'container.build_time' => 1757495598,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX69eX5x');
