<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO1cQtNL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO1cQtNL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO1cQtNL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO1cQtNL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO1cQtNL\App_KernelDevDebugContainer([
    'container.build_hash' => 'O1cQtNL',
    'container.build_id' => 'c4428730',
    'container.build_time' => 1757492021,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO1cQtNL');
